---
- name: "Configure Ethernet Adapter Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthAdapterPolicies
    query_params:
       $filter: "Name eq '{{ name_of_ethernet_adapter_policy }}'"
    api_body: {
          "Name": "{{ name_of_ethernet_adapter_policy }}",
          "Description": "{{ description_of_ethernet_adapter_policy }}",

          "Organization": {
             "Moid": "{{ intersight_org.api_response.Moid }}"
           },


           "AdvancedFilter": false,
           "ArfsSettings": {
              "Enabled": false
           },
           "CompletionQueueSettings": {
              "Count": "{{ completion_queue_count }}",
              "RingSize": "{{ completion_ring_size }}"
           },
           "GeneveEnabled": false,
           "InterruptScaling": false,
           "InterruptSettings": {
              "Count": "{{ number_of_interrupts }}",
              "Mode": "MSIx",
              "CoalescingTime": 125,
              "CoalescingType": "MIN"
           },
           "NvgreSettings": {
              "Enabled": false
           },

           "RoceSettings": {
              "Enabled": false
           },
           "RssHashSettings": {
              "ClassId": "vnic.RssHashSettings",
              "Ipv4Hash": true,
              "Ipv6ExtHash": false,
              "Ipv6Hash": true,
              "ObjectType": "vnic.RssHashSettings",
              "TcpIpv4Hash": true,
              "TcpIpv6ExtHash": false,
              "TcpIpv6Hash": true,
              "UdpIpv4Hash": false,
              "UdpIpv6Hash": false
           },
           "RssSettings": false,
           "RxQueueSettings": {
              "Count": "{{ receive_queue_count }}",
              "RingSize": "{{ receive_ring_size }}"
           },
           "TcpOffloadSettings": {
              "TxChecksum": true,
              "RxChecksum": true,
              "LargeSend": true,
              "LargeReceive": true
           },
           "TxQueueSettings": {
              "Count": "{{ tansmit_queue_count }}",
              "RingSize": "{{ transmit_ring_size }}"
           },
           "UplinkFailbackTimeout": 5,
           "VxlanSettings": {
              "Enabled": false
           }
        }
  register: ethernet_adapter_policy
