#Get Server MOIDs
- name: "Get Server Moid"
  vars:
        api_info: &api_info_moid
          api_private_key: "{{ api_private_key }}"
          api_key_id: "{{ api_key_id }}"
          api_uri: "{{ api_uri | default(omit) }}"
          validate_certs: "{{ validates_certs | default(omit) }}"
          state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_info:
          <<: *api_info_moid
          server_names: "{{ item }}"
  register: server_details
  with_items: "{{ server_name_to_profile_mapping.keys() }}"
