---
- name: "Configure SAN Connectivity Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  block:
  -   cisco.intersight.intersight_rest_api:
          <<: *api_info
          resource_path: /vnic/SanConnectivityPolicies
          query_params:
             $filter: "Name eq '{{ name_of_san_connectivity_policy }}'"
          api_body: {
            "Name": "{{ name_of_san_connectivity_policy }}",
            "Description": "{{ description_of_san_connectivity_policy }}",

            "Organization": {
               "Moid": "{{ intersight_org.api_response.Moid }}"
             },

            "TargetPlatform": "FIAttached",
            "PlacementMode": "auto",
            "WwnnAddressType": "POOL",
            "WwnnPool": "{{ wwnn_pool_details.api_response.Moid }}",
            "StaticWwnnAddress": ""
           }
      register: san_connectivity_policy


  -   cisco.intersight.intersight_rest_api:
          <<: *api_info
          resource_path: /vnic/FcIfs
          query_params:
             $filter: "Name eq '{{ name_of_vhba_1 }}'"
          api_body: {
            "Name": "{{ name_of_vhba_1 }}",
            "Type": "fc-initiator",
            "WwpnAddressType": "POOL",
            "WwpnPool": "{{ wwpn_pool_san_a_details.api_response.Moid }}",
            "Placement": {
              "SwitchId": "A"
            },
            "PersistentBindings": false,
            "FcNetworkPolicy": "{{ fc_network_policy_san_a.api_response.Moid }}",
            "FcQosPolicy": "{{ fc_qos_policy.api_response.Moid }}",
            "FcAdapterPolicy": "{{ fc_adapter_policy.api_response.Moid}}",
            "StaticWwpnAddress": "",
            "SanConnectivityPolicy": "{{ san_connectivity_policy.api_response.Moid }}"
           }


  -   cisco.intersight.intersight_rest_api:
          <<: *api_info
          resource_path: /vnic/FcIfs
          query_params:
             $filter: "Name eq '{{ name_of_vhba_2 }}'"
          api_body: {
            "Name": "{{ name_of_vhba_2 }}",
            "Type": "fc-initiator",
            "WwpnAddressType": "POOL",
            "WwpnPool": "{{ wwpn_pool_san_b_details.api_response.Moid }}",
            "Placement": {
              "SwitchId": "B"
            },
            "PersistentBindings": false,
            "FcNetworkPolicy": "{{ fc_network_policy_san_b.api_response.Moid }}",
            "FcQosPolicy": "{{ fc_qos_policy.api_response.Moid }}",
            "FcAdapterPolicy": "{{ fc_adapter_policy.api_response.Moid}}",
            "StaticWwpnAddress": "",
            "SanConnectivityPolicy": "{{ san_connectivity_policy.api_response.Moid }}"
           }

  when: boot_option == "FC"
