---
- name: "Configure Fibre Channel QoS Policy"
  vars:
    api_info: &api_info_san-a
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info_san-a
      resource_path: /vnic/FcQosPolicies
      query_params:
         $filter: "Name eq '{{ name_of_fc_qos_policy }}'"
      api_body: {
        "Name": "{{ name_of_fc_qos_policy }}",
        "Description": "{{ description_of_fc_qos_policy }}",

        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },

        "RateLimit": 0,
        "MaxDataFieldSize": 2112,
        "Cos": 3,
        "Burst": 10240
       }
  when: boot_option == "FC"
  register: fc_qos_policy
