---
- name: "Configure LAN Connectivity Policy"
  vars:
    api_info: &api_info_fc
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  block:
  - name: "LAN Connectivity Policy for Fibre Channel SAN"
    cisco.intersight.intersight_rest_api:
          <<: *api_info_fc
          resource_path: /vnic/LanConnectivityPolicies
          query_params:
             $filter: "Name eq '{{ name_of_lan_connectivity_policy }}'"
          api_body: {
              "Name": "{{ name_of_lan_connectivity_policy }}",
              "Description": "{{ description_of_lan_connectivity_policy }}",

              "TargetPlatform": "FIAttached",
              "AzureQosEnabled": false,
              "IqnAllocationType": "None",
              "PlacementMode": "auto",
              "IqnPool": "",
              "StaticIqnName": "",

              "Organization": {
                 "Moid": "{{ intersight_org.api_response.Moid }}"
               }
           }
    register: fc_lan_connectivity_policy

  - name: "Add Management vnic to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_fc
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_1 }}'"
      api_body: {
           "Name": "{{ name_of_vnic_1 }}",

           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
           "Placement": {
              "SwitchId": "A"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": true,
           "FabricEthNetworkGroupPolicy": [ "{{ management_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ fc_lan_connectivity_policy.api_response.Moid }}"
       }


  - name: "Add VNIC-2 to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_fc
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_2 }}'"
      api_body: {
           "Name": "{{ name_of_vnic_2 }}",

           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
           "Placement": {
              "SwitchId": "A"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ vmotion_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ fc_lan_connectivity_policy.api_response.Moid }}"
       }


  - name: "Add VNIC-3 to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_fc
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_3 }}'"
      api_body: {
           "Name": "{{ name_of_vnic_3 }}",

           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
           "Placement": {
              "SwitchId": "B"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ vmotion_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ fc_lan_connectivity_policy.api_response.Moid }}"
       }
  when: boot_option == "FC"


- name: "Configure LAN Connectivity Policy for iSCSI SAN"
  vars:
    api_info: &api_info_iscsi
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  block:
  - name: "LAN Connectivity Policy for iSCSI SAN"
    cisco.intersight.intersight_rest_api:
          <<: *api_info_iscsi
          resource_path: /vnic/LanConnectivityPolicies
          query_params:
             $filter: "Name eq '{{ name_of_lan_connectivity_policy }}'"
          api_body: {
              "Name": "{{ name_of_lan_connectivity_policy }}",
              "Description": "{{ description_of_lan_connectivity_policy }}",

              "TargetPlatform": "FIAttached",
              "AzureQosEnabled": false,
              "IqnAllocationType": "Pool",
              "PlacementMode": "auto",
              "IqnPool": "{{ iqn_pool_details.api_response.Moid }}",
              "StaticIqnName": "",

              "Organization": {
                 "Moid": "{{ intersight_org.api_response.Moid }}"
               }
           }
    register: iscsi_lan_connectivity_policy

  - name: "Add VNIC-1 to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_iscsi
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_1 }}'"
        api_body: {
             "Name": "{{ name_of_vnic_1 }}",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
             "Placement": {
                "SwitchId": "A"
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": true,
             "FabricEthNetworkGroupPolicy": [ "{{ management_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ iscsi_lan_connectivity_policy.api_response.Moid }}",
         }


  - name: "Add VNIC-2 to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_iscsi
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_2 }}'"
      api_body: {
           "Name": "{{ name_of_vnic_2 }}",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
           "Placement": {
              "SwitchId": "A"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ vmotion_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ iscsi_lan_connectivity_policy.api_response.Moid }}",
       }


  - name: "Add VNIC-3 to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_iscsi
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_3 }}'"
      api_body: {
           "Name": "{{ name_of_vnic_3 }}",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
           "Placement": {
              "SwitchId": "B"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ vmotion_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ iscsi_lan_connectivity_policy.api_response.Moid }}",
       }

  - name: "Add iSCSI-A vnic to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_iscsi
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_iscsi_a_vnic }}'"
      api_body: {
           "Name": "{{ name_of_iscsi_a_vnic }}",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
           "Placement": {
              "SwitchId": "A"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ iscsi_a_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "IscsiBootPolicy": "{{ iscsi_a_boot_policy.api_response.Moid }}",
           "LanConnectivityPolicy": "{{ iscsi_lan_connectivity_policy.api_response.Moid }}",
       }


  - name: "Add iSCSI-B vnic to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_iscsi
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_iscsi_b_vnic }}'"
      api_body: {
           "Name": "{{ name_of_iscsi_b_vnic }}",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
           "Placement": {
              "SwitchId": "B"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ iscsi_b_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "IscsiBootPolicy": "{{ iscsi_b_boot_policy.api_response.Moid }}",
           "LanConnectivityPolicy": "{{ iscsi_lan_connectivity_policy.api_response.Moid }}",
       }

  when: boot_option == "iSCSI"
